PYMT-1657 Search Adjustments
loyaltycorp/search pull request #33
Opened 2020-01-04 04:51 UTC by merk

This is a PR that contains half a dozen tickets worth of adjustments to achieve a new search approach.

Draft pr.

2020-01-06 00:04 UTC, rashmitsingh reviewed
a couple of questions.

2020-01-06 00:04 UTC, rashmitsingh commented on src/Helpers/RegisteredSearchHandler.php
> +        if ($this->handlersByKey === null) {
will this (stateful class) be a problem that helper is bound as a singleton?

2020-01-06 00:04 UTC, rashmitsingh commented on src/Workers/EntityUpdateWorker.php
> +        return true;
bases on the documentation on the method, should this not default to false?

2020-01-06 00:04 UTC, rashmitsingh commented on tests/TestCase.php
> +abstract class TestCase extends UnitTestCase
💯

2020-01-06 00:06 UTC, merk commented on src/Helpers/RegisteredSearchHandler.php
> +        if ($this->handlersByKey === null) {
The only state we're storing here is based on the DI injections and is just a micro optimisation so we dont have to iterate every handler every time

2020-01-06 00:07 UTC, merk commented on src/Workers/EntityUpdateWorker.php
> +        return true;
If we didnt get an updated entity (we got a deletion instead) we dont have an array of changed properties to compare against - so we just have to notify every time

2020-01-20 23:06 UTC, brendonofficial requested changes
Nice changes 👌

2020-01-20 23:06 UTC, brendonofficial commented on src/Workers/EntityUpdateWorker.php
> +        if ($change instanceof UpdatedEntity === true) {
missing the big `(` and `)`

2020-01-21 04:37 UTC, rashmitsingh approved these changes
looks right.

2020-01-22 02:26 UTC, brendonofficial approved these changes

2020-01-22 03:20 UTC, merged